// <auto-generated />
using System;
using Baykus.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Baykus.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527212546_SacoCosas")]
    partial class SacoCosas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Baykus.Web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Baykus.Web.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Cuil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JornadaLaboralId")
                        .HasColumnType("int");

                    b.Property<string>("Legajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoBaja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("PuestoId")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereCargaHoraria")
                        .HasColumnType("bit");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("JornadaLaboralId");

                    b.HasIndex("PuestoId");

                    b.HasIndex("SectorId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Baykus.Web.Models.EmpleadoHistorialLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JornadaLaboralId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PuestoId")
                        .HasColumnType("int");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("JornadaLaboralId");

                    b.HasIndex("PuestoId");

                    b.HasIndex("SectorId");

                    b.ToTable("EmpleadosHistorialLaboral");
                });

            modelBuilder.Entity("Baykus.Web.Models.Feriado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsNacional")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feriados");
                });

            modelBuilder.Entity("Baykus.Web.Models.JornadaLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly?>("HoraEntradaDefault")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraSalidaDefault")
                        .HasColumnType("time");

                    b.Property<decimal>("HorasDiariasObjetivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasSemanalesObjetivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PermiteHorasExtra")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("JornadasLaborales");
                });

            modelBuilder.Entity("Baykus.Web.Models.ObjetivoOkr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EmpleadoResponsableId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Progreso")
                        .HasColumnType("int");

                    b.Property<int?>("PuestoId")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoResponsableId");

                    b.HasIndex("PuestoId");

                    b.HasIndex("SectorId");

                    b.ToTable("ObjetivosOkr");
                });

            modelBuilder.Entity("Baykus.Web.Models.PlanillaHoraria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("EmpleadoDniSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("EmpleadoNombreSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaHasta")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaPresentacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRechazo")
                        .HasColumnType("datetime2");

                    b.Property<string>("JornadaNombreSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionAprobador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PuestoNombreSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorNombreSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalHorasExtra100")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalHorasExtra50")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalHorasFeriado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalHorasNocturnas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalHorasNormales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalHorasTrabajadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioAprobacionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCargaId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("PlanillasHorarias");
                });

            modelBuilder.Entity("Baykus.Web.Models.PlanillaHorariaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsFeriado")
                        .HasColumnType("bit");

                    b.Property<bool>("EsFinDeSemana")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly?>("HoraEntrada")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<decimal>("HorasExtra100")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasExtra50")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasFeriado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasNocturnas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasNormales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinutosDescanso")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanillaHorariaId")
                        .HasColumnType("int");

                    b.Property<string>("TareaRealizada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDia")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalHoras")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlanillaHorariaId");

                    b.ToTable("PlanillasHorariasDetalles");
                });

            modelBuilder.Entity("Baykus.Web.Models.PlanillaHorariaHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanillaHorariaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlanillaHorariaId");

                    b.ToTable("PlanillasHorariasHistorial");
                });

            modelBuilder.Entity("Baykus.Web.Models.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("Baykus.Web.Models.ResultadoClaveOkr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ObjetivoOkrId")
                        .HasColumnType("int");

                    b.Property<int>("Progreso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoOkrId");

                    b.ToTable("ResultadosClaveOkr");
                });

            modelBuilder.Entity("Baykus.Web.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("Baykus.Web.Models.SeguimientoOkr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ObjetivoOkrId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoOkrId");

                    b.ToTable("SeguimientosOkr");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Baykus.Web.Models.Empleado", b =>
                {
                    b.HasOne("Baykus.Web.Models.JornadaLaboral", "JornadaLaboral")
                        .WithMany("Empleados")
                        .HasForeignKey("JornadaLaboralId");

                    b.HasOne("Baykus.Web.Models.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId");

                    b.HasOne("Baykus.Web.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId");

                    b.Navigation("JornadaLaboral");

                    b.Navigation("Puesto");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Baykus.Web.Models.EmpleadoHistorialLaboral", b =>
                {
                    b.HasOne("Baykus.Web.Models.Empleado", "Empleado")
                        .WithMany("HistorialLaboral")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Baykus.Web.Models.JornadaLaboral", "JornadaLaboral")
                        .WithMany()
                        .HasForeignKey("JornadaLaboralId");

                    b.HasOne("Baykus.Web.Models.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId");

                    b.HasOne("Baykus.Web.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId");

                    b.Navigation("Empleado");

                    b.Navigation("JornadaLaboral");

                    b.Navigation("Puesto");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Baykus.Web.Models.ObjetivoOkr", b =>
                {
                    b.HasOne("Baykus.Web.Models.Empleado", "EmpleadoResponsable")
                        .WithMany()
                        .HasForeignKey("EmpleadoResponsableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Baykus.Web.Models.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId");

                    b.HasOne("Baykus.Web.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpleadoResponsable");

                    b.Navigation("Puesto");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Baykus.Web.Models.PlanillaHoraria", b =>
                {
                    b.HasOne("Baykus.Web.Models.Empleado", "Empleado")
                        .WithMany("PlanillasHorarias")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Baykus.Web.Models.PlanillaHorariaDetalle", b =>
                {
                    b.HasOne("Baykus.Web.Models.PlanillaHoraria", "PlanillaHoraria")
                        .WithMany("Detalles")
                        .HasForeignKey("PlanillaHorariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanillaHoraria");
                });

            modelBuilder.Entity("Baykus.Web.Models.PlanillaHorariaHistorial", b =>
                {
                    b.HasOne("Baykus.Web.Models.PlanillaHoraria", "PlanillaHoraria")
                        .WithMany()
                        .HasForeignKey("PlanillaHorariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanillaHoraria");
                });

            modelBuilder.Entity("Baykus.Web.Models.Puesto", b =>
                {
                    b.HasOne("Baykus.Web.Models.Sector", "Sector")
                        .WithMany("Puestos")
                        .HasForeignKey("SectorId");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Baykus.Web.Models.ResultadoClaveOkr", b =>
                {
                    b.HasOne("Baykus.Web.Models.ObjetivoOkr", "ObjetivoOkr")
                        .WithMany("ResultadosClave")
                        .HasForeignKey("ObjetivoOkrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjetivoOkr");
                });

            modelBuilder.Entity("Baykus.Web.Models.SeguimientoOkr", b =>
                {
                    b.HasOne("Baykus.Web.Models.ObjetivoOkr", "ObjetivoOkr")
                        .WithMany("Seguimientos")
                        .HasForeignKey("ObjetivoOkrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjetivoOkr");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Baykus.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Baykus.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Baykus.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Baykus.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Baykus.Web.Models.Empleado", b =>
                {
                    b.Navigation("HistorialLaboral");

                    b.Navigation("PlanillasHorarias");
                });

            modelBuilder.Entity("Baykus.Web.Models.JornadaLaboral", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Baykus.Web.Models.ObjetivoOkr", b =>
                {
                    b.Navigation("ResultadosClave");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("Baykus.Web.Models.PlanillaHoraria", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Baykus.Web.Models.Sector", b =>
                {
                    b.Navigation("Puestos");
                });
#pragma warning restore 612, 618
        }
    }
}
